// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/argus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage é qualquer mensagem enviada pelo agente ao servidor.
type AgentMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Metrics
	//	*AgentMessage_Result
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_argus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_argus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_argus_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_Result) isAgentMessage_Payload() {}

// ServerCommand é qualquer comando enviado pelo servidor ao agente.
type ServerCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerCommand_Service
	//	*ServerCommand_Shell
	Payload       isServerCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_proto_argus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_argus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_proto_argus_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ServerCommand) GetPayload() isServerCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerCommand) GetService() *ServiceCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerCommand_Service); ok {
			return x.Service
		}
	}
	return nil
}

func (x *ServerCommand) GetShell() *ShellCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerCommand_Shell); ok {
			return x.Shell
		}
	}
	return nil
}

type isServerCommand_Payload interface {
	isServerCommand_Payload()
}

type ServerCommand_Service struct {
	Service *ServiceCommand `protobuf:"bytes,2,opt,name=service,proto3,oneof"`
}

type ServerCommand_Shell struct {
	Shell *ShellCommand `protobuf:"bytes,3,opt,name=shell,proto3,oneof"`
}

func (*ServerCommand_Service) isServerCommand_Payload() {}

func (*ServerCommand_Shell) isServerCommand_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_argus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_argus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_argus_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamPercent    float32                `protobuf:"fixed32,2,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"`
	DiskPercent   float32                `protobuf:"fixed32,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_argus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_argus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_argus_proto_rawDescGZIP(), []int{3}
}

func (x *Metrics) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Metrics) GetRamPercent() float32 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}

func (x *Metrics) GetDiskPercent() float32 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

type ServiceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // start | stop | restart | status
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCommand) Reset() {
	*x = ServiceCommand{}
	mi := &file_proto_argus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCommand) ProtoMessage() {}

func (x *ServiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_argus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCommand.ProtoReflect.Descriptor instead.
func (*ServiceCommand) Descriptor() ([]byte, []int) {
	return file_proto_argus_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServiceCommand) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ShellCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCommand) Reset() {
	*x = ShellCommand{}
	mi := &file_proto_argus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommand) ProtoMessage() {}

func (x *ShellCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_argus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommand.ProtoReflect.Descriptor instead.
func (*ShellCommand) Descriptor() ([]byte, []int) {
	return file_proto_argus_proto_rawDescGZIP(), []int{5}
}

func (x *ShellCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_argus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_argus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_argus_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_proto_argus_proto protoreflect.FileDescriptor

const file_proto_argus_proto_rawDesc = "" +
	"\n" +
	"\x11proto/argus.proto\x12\x05argus\"\xc2\x01\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x120\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.argus.HeartbeatH\x00R\theartbeat\x12*\n" +
	"\ametrics\x18\x03 \x01(\v2\x0e.argus.MetricsH\x00R\ametrics\x12.\n" +
	"\x06result\x18\x04 \x01(\v2\x14.argus.CommandResultH\x00R\x06resultB\t\n" +
	"\apayload\"\x99\x01\n" +
	"\rServerCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x121\n" +
	"\aservice\x18\x02 \x01(\v2\x15.argus.ServiceCommandH\x00R\aservice\x12+\n" +
	"\x05shell\x18\x03 \x01(\v2\x13.argus.ShellCommandH\x00R\x05shellB\t\n" +
	"\apayload\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"n\n" +
	"\aMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vram_percent\x18\x02 \x01(\x02R\n" +
	"ramPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x02R\vdiskPercent\"B\n" +
	"\x0eServiceCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"(\n" +
	"\fShellCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"c\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode2H\n" +
	"\fAgentService\x128\n" +
	"\aConnect\x12\x13.argus.AgentMessage\x1a\x14.argus.ServerCommand(\x010\x01B!Z\x1fgithub.com/jtave111/argus/protob\x06proto3"

var (
	file_proto_argus_proto_rawDescOnce sync.Once
	file_proto_argus_proto_rawDescData []byte
)

func file_proto_argus_proto_rawDescGZIP() []byte {
	file_proto_argus_proto_rawDescOnce.Do(func() {
		file_proto_argus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_argus_proto_rawDesc), len(file_proto_argus_proto_rawDesc)))
	})
	return file_proto_argus_proto_rawDescData
}

var file_proto_argus_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_argus_proto_goTypes = []any{
	(*AgentMessage)(nil),   // 0: argus.AgentMessage
	(*ServerCommand)(nil),  // 1: argus.ServerCommand
	(*Heartbeat)(nil),      // 2: argus.Heartbeat
	(*Metrics)(nil),        // 3: argus.Metrics
	(*ServiceCommand)(nil), // 4: argus.ServiceCommand
	(*ShellCommand)(nil),   // 5: argus.ShellCommand
	(*CommandResult)(nil),  // 6: argus.CommandResult
}
var file_proto_argus_proto_depIdxs = []int32{
	2, // 0: argus.AgentMessage.heartbeat:type_name -> argus.Heartbeat
	3, // 1: argus.AgentMessage.metrics:type_name -> argus.Metrics
	6, // 2: argus.AgentMessage.result:type_name -> argus.CommandResult
	4, // 3: argus.ServerCommand.service:type_name -> argus.ServiceCommand
	5, // 4: argus.ServerCommand.shell:type_name -> argus.ShellCommand
	0, // 5: argus.AgentService.Connect:input_type -> argus.AgentMessage
	1, // 6: argus.AgentService.Connect:output_type -> argus.ServerCommand
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_argus_proto_init() }
func file_proto_argus_proto_init() {
	if File_proto_argus_proto != nil {
		return
	}
	file_proto_argus_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_Result)(nil),
	}
	file_proto_argus_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerCommand_Service)(nil),
		(*ServerCommand_Shell)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_argus_proto_rawDesc), len(file_proto_argus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_argus_proto_goTypes,
		DependencyIndexes: file_proto_argus_proto_depIdxs,
		MessageInfos:      file_proto_argus_proto_msgTypes,
	}.Build()
	File_proto_argus_proto = out.File
	file_proto_argus_proto_goTypes = nil
	file_proto_argus_proto_depIdxs = nil
}
