// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Agent struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	NetworkID          uuid.UUID      `db:"network_id" json:"network_id"`
	TokenHash          string         `db:"token_hash" json:"token_hash"`
	Hostname           string         `db:"hostname" json:"hostname"`
	Fqdn               sql.NullString `db:"fqdn" json:"fqdn"`
	Os                 string         `db:"os" json:"os"`
	Distro             sql.NullString `db:"distro" json:"distro"`
	Arch               string         `db:"arch" json:"arch"`
	KernelVersion      sql.NullString `db:"kernel_version" json:"kernel_version"`
	IpAddress          string         `db:"ip_address" json:"ip_address"`
	MacAddress         sql.NullString `db:"mac_address" json:"mac_address"`
	AgentVersion       string         `db:"agent_version" json:"agent_version"`
	IsOnline           bool           `db:"is_online" json:"is_online"`
	LastSeen           sql.NullTime   `db:"last_seen" json:"last_seen"`
	Latitude           sql.NullString `db:"latitude" json:"latitude"`
	Longitude          sql.NullString `db:"longitude" json:"longitude"`
	LocationName       sql.NullString `db:"location_name" json:"location_name"`
	City               sql.NullString `db:"city" json:"city"`
	CountryCode        sql.NullString `db:"country_code" json:"country_code"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UserOrganizationID uuid.NullUUID  `db:"user_organization_id" json:"user_organization_id"`
	OsUser             sql.NullString `db:"os_user" json:"os_user"`
	OsUserFullname     sql.NullString `db:"os_user_fullname" json:"os_user_fullname"`
	OsUserEmail        sql.NullString `db:"os_user_email" json:"os_user_email"`
}

type AgentHardware struct {
	AgentID        uuid.UUID `db:"agent_id" json:"agent_id"`
	CpuModel       string    `db:"cpu_model" json:"cpu_model"`
	CpuCores       int32     `db:"cpu_cores" json:"cpu_cores"`
	CpuThreads     int32     `db:"cpu_threads" json:"cpu_threads"`
	RamTotalBytes  int64     `db:"ram_total_bytes" json:"ram_total_bytes"`
	DiskTotalBytes int64     `db:"disk_total_bytes" json:"disk_total_bytes"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

type AgentNetworkInterface struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	AgentID       uuid.UUID      `db:"agent_id" json:"agent_id"`
	InterfaceName string         `db:"interface_name" json:"interface_name"`
	IpAddress     string         `db:"ip_address" json:"ip_address"`
	MacAddress    sql.NullString `db:"mac_address" json:"mac_address"`
	SpeedMbps     sql.NullInt32  `db:"speed_mbps" json:"speed_mbps"`
	IsUp          bool           `db:"is_up" json:"is_up"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
}

type AuditLog struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	OrganizationID uuid.NullUUID  `db:"organization_id" json:"organization_id"`
	UserID         uuid.NullUUID  `db:"user_id" json:"user_id"`
	Action         string         `db:"action" json:"action"`
	TargetType     string         `db:"target_type" json:"target_type"`
	TargetID       uuid.NullUUID  `db:"target_id" json:"target_id"`
	IpAddress      string         `db:"ip_address" json:"ip_address"`
	UserAgent      sql.NullString `db:"user_agent" json:"user_agent"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}

type CommandResult struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	AgentID    uuid.UUID      `db:"agent_id" json:"agent_id"`
	CommandID  string         `db:"command_id" json:"command_id"`
	CommandStr string         `db:"command_str" json:"command_str"`
	Output     sql.NullString `db:"output" json:"output"`
	ExitCode   int32          `db:"exit_code" json:"exit_code"`
	ExecutedAt time.Time      `db:"executed_at" json:"executed_at"`
}

type Metric struct {
	ID          int64         `db:"id" json:"id"`
	AgentID     uuid.UUID     `db:"agent_id" json:"agent_id"`
	CpuPercent  float32       `db:"cpu_percent" json:"cpu_percent"`
	RamPercent  float32       `db:"ram_percent" json:"ram_percent"`
	DiskPercent float32       `db:"disk_percent" json:"disk_percent"`
	NetInKbps   sql.NullInt32 `db:"net_in_kbps" json:"net_in_kbps"`
	NetOutKbps  sql.NullInt32 `db:"net_out_kbps" json:"net_out_kbps"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
}

type Network struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	OrganizationID uuid.UUID      `db:"organization_id" json:"organization_id"`
	Name           string         `db:"name" json:"name"`
	Description    sql.NullString `db:"description" json:"description"`
	Type           string         `db:"type" json:"type"`
	Subnet         string         `db:"subnet" json:"subnet"`
	Gateway        sql.NullString `db:"gateway" json:"gateway"`
	DnsPrimary     sql.NullString `db:"dns_primary" json:"dns_primary"`
	DnsSecondary   sql.NullString `db:"dns_secondary" json:"dns_secondary"`
	VlanID         sql.NullInt32  `db:"vlan_id" json:"vlan_id"`
	Latitude       sql.NullString `db:"latitude" json:"latitude"`
	Longitude      sql.NullString `db:"longitude" json:"longitude"`
	LocationName   sql.NullString `db:"location_name" json:"location_name"`
	Address        sql.NullString `db:"address" json:"address"`
	City           sql.NullString `db:"city" json:"city"`
	CountryCode    string         `db:"country_code" json:"country_code"`
	IsActive       bool           `db:"is_active" json:"is_active"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}

type NetworkTopology struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	NetworkAID  uuid.UUID      `db:"network_a_id" json:"network_a_id"`
	NetworkBID  uuid.UUID      `db:"network_b_id" json:"network_b_id"`
	LinkType    string         `db:"link_type" json:"link_type"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
}

type Organization struct {
	ID                   uuid.UUID      `db:"id" json:"id"`
	Name                 string         `db:"name" json:"name"`
	Slug                 string         `db:"slug" json:"slug"`
	Email                string         `db:"email" json:"email"`
	PasswordHash         string         `db:"password_hash" json:"password_hash"`
	TotpSecret           sql.NullString `db:"totp_secret" json:"totp_secret"`
	AgentRegistrationKey string         `db:"agent_registration_key" json:"agent_registration_key"`
	IpAllowlist          []string       `db:"ip_allowlist" json:"ip_allowlist"`
	IsActive             bool           `db:"is_active" json:"is_active"`
	Plan                 string         `db:"plan" json:"plan"`
	CreatedAt            time.Time      `db:"created_at" json:"created_at"`
}

type OrganizationInvite struct {
	ID             uuid.UUID    `db:"id" json:"id"`
	OrganizationID uuid.UUID    `db:"organization_id" json:"organization_id"`
	Email          string       `db:"email" json:"email"`
	Token          string       `db:"token" json:"token"`
	Role           string       `db:"role" json:"role"`
	ExpiresAt      time.Time    `db:"expires_at" json:"expires_at"`
	UsedAt         sql.NullTime `db:"used_at" json:"used_at"`
	CreatedAt      time.Time    `db:"created_at" json:"created_at"`
}

type Service struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	AgentID         uuid.UUID      `db:"agent_id" json:"agent_id"`
	Name            string         `db:"name" json:"name"`
	DisplayName     string         `db:"display_name" json:"display_name"`
	Description     sql.NullString `db:"description" json:"description"`
	Type            string         `db:"type" json:"type"`
	Status          string         `db:"status" json:"status"`
	Enabled         bool           `db:"enabled" json:"enabled"`
	Pid             sql.NullInt32  `db:"pid" json:"pid"`
	RunAsUser       sql.NullString `db:"run_as_user" json:"run_as_user"`
	Port            sql.NullInt32  `db:"port" json:"port"`
	Protocol        sql.NullString `db:"protocol" json:"protocol"`
	RestartPolicy   sql.NullString `db:"restart_policy" json:"restart_policy"`
	HealthCheckCmd  sql.NullString `db:"health_check_cmd" json:"health_check_cmd"`
	HealthCheckUrl  sql.NullString `db:"health_check_url" json:"health_check_url"`
	LastHealthCheck sql.NullTime   `db:"last_health_check" json:"last_health_check"`
	HealthStatus    sql.NullString `db:"health_status" json:"health_status"`
	UptimeSeconds   int64          `db:"uptime_seconds" json:"uptime_seconds"`
	UpdatedAt       time.Time      `db:"updated_at" json:"updated_at"`
}

type ServiceDependency struct {
	ServiceID   uuid.UUID `db:"service_id" json:"service_id"`
	DependsOnID uuid.UUID `db:"depends_on_id" json:"depends_on_id"`
}

type User struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	Email        string         `db:"email" json:"email"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	TotpSecret   sql.NullString `db:"totp_secret" json:"totp_secret"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	LastLoginAt  sql.NullTime   `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

type UserOrganization struct {
	ID             uuid.UUID     `db:"id" json:"id"`
	UserID         uuid.UUID     `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID     `db:"organization_id" json:"organization_id"`
	Role           string        `db:"role" json:"role"`
	InvitedBy      uuid.NullUUID `db:"invited_by" json:"invited_by"`
	AcceptedAt     sql.NullTime  `db:"accepted_at" json:"accepted_at"`
	CreatedAt      time.Time     `db:"created_at" json:"created_at"`
}
