// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptOrganizationInvite(ctx context.Context, arg AcceptOrganizationInviteParams) error
	// ============================================================
	// USER_ORGANIZATIONS
	// ============================================================
	AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) (UserOrganization, error)
	// ============================================================
	// ORGANIZATION_INVITES
	// ============================================================
	CreateInvite(ctx context.Context, arg CreateInviteParams) (OrganizationInvite, error)
	// ============================================================
	// NETWORKS
	// ============================================================
	CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error)
	// ============================================================
	// ORGANIZATIONS
	// ============================================================
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// ============================================================
	// USERS
	// ============================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// TODO: escreva uma query para desativar uma network (is_active = false) pelo id
	DeactivateNetwork(ctx context.Context, id uuid.UUID) error
	// TODO: escreva uma query para desativar um usuário (is_active = false) pelo id
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	// TTL: apaga métricas mais antigas que X. Ex: $1 = '30 days'
	DeleteOldMetrics(ctx context.Context, dollar_1 int64) error
	GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error)
	GetAgentByTokenHash(ctx context.Context, tokenHash string) (Agent, error)
	GetAgentHardware(ctx context.Context, agentID uuid.UUID) (AgentHardware, error)
	GetCommandResult(ctx context.Context, commandID string) (CommandResult, error)
	GetInviteByToken(ctx context.Context, token string) (OrganizationInvite, error)
	GetLatestMetric(ctx context.Context, agentID uuid.UUID) (Metric, error)
	GetNetworkByID(ctx context.Context, id uuid.UUID) (Network, error)
	GetOrganizationByAgentKey(ctx context.Context, agentRegistrationKey string) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error)
	// ============================================================
	// AUDIT_LOGS
	// ============================================================
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// ============================================================
	// COMMAND_RESULTS
	// ============================================================
	InsertCommandResult(ctx context.Context, arg InsertCommandResultParams) (CommandResult, error)
	// ============================================================
	// METRICS
	// ============================================================
	InsertMetric(ctx context.Context, arg InsertMetricParams) (Metric, error)
	ListAgentsByNetwork(ctx context.Context, networkID uuid.UUID) ([]Agent, error)
	// TODO: escreva uma query que lista todos os agents de uma organização inteira
	// (join agents → networks filtrando por networks.organization_id)
	ListAgentsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Agent, error)
	// TODO: escreva uma query que lista os últimos N resultados de comandos de um agent
	// dica: use LIMIT $2 e ORDER BY executed_at DESC
	ListCommandResultsByAgent(ctx context.Context, arg ListCommandResultsByAgentParams) ([]CommandResult, error)
	// TODO: escreva uma query que retorna as métricas de um agent a partir de uma data ($2)
	// útil para montar gráficos no dashboard
	ListMetricsSince(ctx context.Context, agentID uuid.UUID) ([]Metric, error)
	ListNetworksByOrg(ctx context.Context, organizationID uuid.UUID) ([]Network, error)
	// TODO: escreva uma query que lista todos os membros de uma organização
	// (join users + user_organizations filtrando por organization_id)
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	// TODO: escreva uma query que retorna todas as organizations onde um user está inserido
	// (join entre organizations e user_organizations filtrando por user_id e accepted_at IS NOT NULL)
	ListOrganizationsByUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsByUserRow, error)
	ListServicesByAgent(ctx context.Context, agentID uuid.UUID) ([]Service, error)
	// ============================================================
	// AGENTS
	// ============================================================
	RegisterAgent(ctx context.Context, arg RegisterAgentParams) (Agent, error)
	SetAgentOffline(ctx context.Context, id uuid.UUID) error
	// marca offline todos os agents que não mandam heartbeat há X tempo
	// $1 é um intervalo: ex '2 minutes'
	SetOfflineAgentsSince(ctx context.Context, dollar_1 int64) error
	UpdateAgentLastSeen(ctx context.Context, id uuid.UUID) error
	// TODO: escreva uma query para atualizar o health_status e last_health_check de um serviço pelo id
	UpdateServiceHealth(ctx context.Context, arg UpdateServiceHealthParams) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	// ============================================================
	// AGENT_HARDWARE
	// ============================================================
	UpsertAgentHardware(ctx context.Context, arg UpsertAgentHardwareParams) (AgentHardware, error)
	// ============================================================
	// SERVICES
	// ============================================================
	UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error)
	UseInvite(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
