// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const acceptOrganizationInvite = `-- name: AcceptOrganizationInvite :exec
UPDATE user_organizations SET accepted_at = NOW()
WHERE user_id = $1 AND organization_id = $2
`

type AcceptOrganizationInviteParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) AcceptOrganizationInvite(ctx context.Context, arg AcceptOrganizationInviteParams) error {
	_, err := q.db.ExecContext(ctx, acceptOrganizationInvite, arg.UserID, arg.OrganizationID)
	return err
}

const addServiceDependency = `-- name: AddServiceDependency :exec

INSERT INTO service_dependencies (service_id, depends_on_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddServiceDependencyParams struct {
	ServiceID   uuid.UUID `db:"service_id" json:"service_id"`
	DependsOnID uuid.UUID `db:"depends_on_id" json:"depends_on_id"`
}

// ============================================================
// SERVICE_DEPENDENCIES
// ============================================================
func (q *Queries) AddServiceDependency(ctx context.Context, arg AddServiceDependencyParams) error {
	_, err := q.db.ExecContext(ctx, addServiceDependency, arg.ServiceID, arg.DependsOnID)
	return err
}

const addUserToOrganization = `-- name: AddUserToOrganization :one

INSERT INTO user_organizations (user_id, organization_id, role, invited_by)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, organization_id, role, invited_by, accepted_at, created_at
`

type AddUserToOrganizationParams struct {
	UserID         uuid.UUID     `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID     `db:"organization_id" json:"organization_id"`
	Role           string        `db:"role" json:"role"`
	InvitedBy      uuid.NullUUID `db:"invited_by" json:"invited_by"`
}

// ============================================================
// USER_ORGANIZATIONS
// ============================================================
func (q *Queries) AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) (UserOrganization, error) {
	row := q.db.QueryRowContext(ctx, addUserToOrganization,
		arg.UserID,
		arg.OrganizationID,
		arg.Role,
		arg.InvitedBy,
	)
	var i UserOrganization
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const bindAgentToUserOrg = `-- name: BindAgentToUserOrg :exec
UPDATE agents
SET user_organization_id = $2, os_user = $3, os_user_fullname = $4, os_user_email = $5
WHERE id = $1
`

type BindAgentToUserOrgParams struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	UserOrganizationID uuid.NullUUID  `db:"user_organization_id" json:"user_organization_id"`
	OsUser             sql.NullString `db:"os_user" json:"os_user"`
	OsUserFullname     sql.NullString `db:"os_user_fullname" json:"os_user_fullname"`
	OsUserEmail        sql.NullString `db:"os_user_email" json:"os_user_email"`
}

func (q *Queries) BindAgentToUserOrg(ctx context.Context, arg BindAgentToUserOrgParams) error {
	_, err := q.db.ExecContext(ctx, bindAgentToUserOrg,
		arg.ID,
		arg.UserOrganizationID,
		arg.OsUser,
		arg.OsUserFullname,
		arg.OsUserEmail,
	)
	return err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO organization_invites (organization_id, email, token, role, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, email, token, role, expires_at, used_at, created_at
`

type CreateInviteParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Email          string    `db:"email" json:"email"`
	Token          string    `db:"token" json:"token"`
	Role           string    `db:"role" json:"role"`
	ExpiresAt      time.Time `db:"expires_at" json:"expires_at"`
}

// ============================================================
// ORGANIZATION_INVITES
// ============================================================
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.OrganizationID,
		arg.Email,
		arg.Token,
		arg.Role,
		arg.ExpiresAt,
	)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNetwork = `-- name: CreateNetwork :one

INSERT INTO networks (organization_id, name, description, type, subnet, gateway, dns_primary, dns_secondary, vlan_id, latitude, longitude, location_name, address, city, country_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, organization_id, name, description, type, subnet, gateway, dns_primary, dns_secondary, vlan_id, latitude, longitude, location_name, address, city, country_code, is_active, created_at
`

type CreateNetworkParams struct {
	OrganizationID uuid.UUID      `db:"organization_id" json:"organization_id"`
	Name           string         `db:"name" json:"name"`
	Description    sql.NullString `db:"description" json:"description"`
	Type           string         `db:"type" json:"type"`
	Subnet         string         `db:"subnet" json:"subnet"`
	Gateway        sql.NullString `db:"gateway" json:"gateway"`
	DnsPrimary     sql.NullString `db:"dns_primary" json:"dns_primary"`
	DnsSecondary   sql.NullString `db:"dns_secondary" json:"dns_secondary"`
	VlanID         sql.NullInt32  `db:"vlan_id" json:"vlan_id"`
	Latitude       sql.NullString `db:"latitude" json:"latitude"`
	Longitude      sql.NullString `db:"longitude" json:"longitude"`
	LocationName   sql.NullString `db:"location_name" json:"location_name"`
	Address        sql.NullString `db:"address" json:"address"`
	City           sql.NullString `db:"city" json:"city"`
	CountryCode    string         `db:"country_code" json:"country_code"`
}

// ============================================================
// NETWORKS
// ============================================================
func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRowContext(ctx, createNetwork,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Subnet,
		arg.Gateway,
		arg.DnsPrimary,
		arg.DnsSecondary,
		arg.VlanID,
		arg.Latitude,
		arg.Longitude,
		arg.LocationName,
		arg.Address,
		arg.City,
		arg.CountryCode,
	)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Subnet,
		&i.Gateway,
		&i.DnsPrimary,
		&i.DnsSecondary,
		&i.VlanID,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.Address,
		&i.City,
		&i.CountryCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createNetworkTopologyLink = `-- name: CreateNetworkTopologyLink :one

INSERT INTO network_topology (network_a_id, network_b_id, link_type, description)
VALUES ($1, $2, $3, $4)
RETURNING id, network_a_id, network_b_id, link_type, description, created_at
`

type CreateNetworkTopologyLinkParams struct {
	NetworkAID  uuid.UUID      `db:"network_a_id" json:"network_a_id"`
	NetworkBID  uuid.UUID      `db:"network_b_id" json:"network_b_id"`
	LinkType    string         `db:"link_type" json:"link_type"`
	Description sql.NullString `db:"description" json:"description"`
}

// ============================================================
// NETWORK_TOPOLOGY
// ============================================================
func (q *Queries) CreateNetworkTopologyLink(ctx context.Context, arg CreateNetworkTopologyLinkParams) (NetworkTopology, error) {
	row := q.db.QueryRowContext(ctx, createNetworkTopologyLink,
		arg.NetworkAID,
		arg.NetworkBID,
		arg.LinkType,
		arg.Description,
	)
	var i NetworkTopology
	err := row.Scan(
		&i.ID,
		&i.NetworkAID,
		&i.NetworkBID,
		&i.LinkType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one

INSERT INTO organizations (name, slug, email, password_hash, agent_registration_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, email, password_hash, totp_secret, agent_registration_key, ip_allowlist, is_active, plan, created_at
`

type CreateOrganizationParams struct {
	Name                 string `db:"name" json:"name"`
	Slug                 string `db:"slug" json:"slug"`
	Email                string `db:"email" json:"email"`
	PasswordHash         string `db:"password_hash" json:"password_hash"`
	AgentRegistrationKey string `db:"agent_registration_key" json:"agent_registration_key"`
}

// ============================================================
// ORGANIZATIONS
// ============================================================
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.Email,
		arg.PasswordHash,
		arg.AgentRegistrationKey,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.AgentRegistrationKey,
		pq.Array(&i.IpAllowlist),
		&i.IsActive,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, totp_secret, is_active, last_login_at, created_at
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

// ============================================================
// USERS
// ============================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateNetwork = `-- name: DeactivateNetwork :exec
UPDATE networks SET is_active = FALSE
WHERE id = $1
`

// TODO: escreva uma query para desativar uma network (is_active = false) pelo id
func (q *Queries) DeactivateNetwork(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateNetwork, id)
	return err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = FALSE
WHERE id = $1
`

// TODO: escreva uma query para desativar um usuário (is_active = false) pelo id
func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, id)
	return err
}

const deleteAgentNetworkInterfaces = `-- name: DeleteAgentNetworkInterfaces :exec
DELETE FROM agent_network_interfaces
WHERE agent_id = $1
`

func (q *Queries) DeleteAgentNetworkInterfaces(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAgentNetworkInterfaces, agentID)
	return err
}

const deleteNetworkTopologyLink = `-- name: DeleteNetworkTopologyLink :exec
DELETE FROM network_topology
WHERE id = $1
`

func (q *Queries) DeleteNetworkTopologyLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNetworkTopologyLink, id)
	return err
}

const deleteOldMetrics = `-- name: DeleteOldMetrics :exec
DELETE FROM metrics
WHERE created_at < NOW() - ($1::interval)
`

// TTL: apaga métricas mais antigas que X. Ex: $1 = '30 days'
func (q *Queries) DeleteOldMetrics(ctx context.Context, dollar_1 string) error {
	_, err := q.db.ExecContext(ctx, deleteOldMetrics, dollar_1)
	return err
}

const deleteServiceDependency = `-- name: DeleteServiceDependency :exec
DELETE FROM service_dependencies
WHERE service_id = $1 AND depends_on_id = $2
`

type DeleteServiceDependencyParams struct {
	ServiceID   uuid.UUID `db:"service_id" json:"service_id"`
	DependsOnID uuid.UUID `db:"depends_on_id" json:"depends_on_id"`
}

func (q *Queries) DeleteServiceDependency(ctx context.Context, arg DeleteServiceDependencyParams) error {
	_, err := q.db.ExecContext(ctx, deleteServiceDependency, arg.ServiceID, arg.DependsOnID)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, network_id, token_hash, hostname, fqdn, os, distro, arch, kernel_version, ip_address, mac_address, agent_version, is_online, last_seen, latitude, longitude, location_name, city, country_code, created_at, user_organization_id, os_user, os_user_fullname, os_user_email FROM agents WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.TokenHash,
		&i.Hostname,
		&i.Fqdn,
		&i.Os,
		&i.Distro,
		&i.Arch,
		&i.KernelVersion,
		&i.IpAddress,
		&i.MacAddress,
		&i.AgentVersion,
		&i.IsOnline,
		&i.LastSeen,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.City,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UserOrganizationID,
		&i.OsUser,
		&i.OsUserFullname,
		&i.OsUserEmail,
	)
	return i, err
}

const getAgentByTokenHash = `-- name: GetAgentByTokenHash :one
SELECT id, network_id, token_hash, hostname, fqdn, os, distro, arch, kernel_version, ip_address, mac_address, agent_version, is_online, last_seen, latitude, longitude, location_name, city, country_code, created_at, user_organization_id, os_user, os_user_fullname, os_user_email FROM agents WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAgentByTokenHash(ctx context.Context, tokenHash string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByTokenHash, tokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.TokenHash,
		&i.Hostname,
		&i.Fqdn,
		&i.Os,
		&i.Distro,
		&i.Arch,
		&i.KernelVersion,
		&i.IpAddress,
		&i.MacAddress,
		&i.AgentVersion,
		&i.IsOnline,
		&i.LastSeen,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.City,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UserOrganizationID,
		&i.OsUser,
		&i.OsUserFullname,
		&i.OsUserEmail,
	)
	return i, err
}

const getAgentHardware = `-- name: GetAgentHardware :one
SELECT agent_id, cpu_model, cpu_cores, cpu_threads, ram_total_bytes, disk_total_bytes, updated_at FROM agent_hardware WHERE agent_id = $1
`

func (q *Queries) GetAgentHardware(ctx context.Context, agentID uuid.UUID) (AgentHardware, error) {
	row := q.db.QueryRowContext(ctx, getAgentHardware, agentID)
	var i AgentHardware
	err := row.Scan(
		&i.AgentID,
		&i.CpuModel,
		&i.CpuCores,
		&i.CpuThreads,
		&i.RamTotalBytes,
		&i.DiskTotalBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommandResult = `-- name: GetCommandResult :one
SELECT id, agent_id, command_id, command_str, output, exit_code, executed_at FROM command_results
WHERE command_id = $1 LIMIT 1
`

func (q *Queries) GetCommandResult(ctx context.Context, commandID string) (CommandResult, error) {
	row := q.db.QueryRowContext(ctx, getCommandResult, commandID)
	var i CommandResult
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CommandID,
		&i.CommandStr,
		&i.Output,
		&i.ExitCode,
		&i.ExecutedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, organization_id, email, token, role, expires_at, used_at, created_at FROM organization_invites
WHERE token = $1 AND used_at IS NULL AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (OrganizationInvite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByToken, token)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestMetric = `-- name: GetLatestMetric :one
SELECT id, agent_id, cpu_percent, ram_percent, disk_percent, net_in_kbps, net_out_kbps, created_at FROM metrics
WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMetric(ctx context.Context, agentID uuid.UUID) (Metric, error) {
	row := q.db.QueryRowContext(ctx, getLatestMetric, agentID)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CpuPercent,
		&i.RamPercent,
		&i.DiskPercent,
		&i.NetInKbps,
		&i.NetOutKbps,
		&i.CreatedAt,
	)
	return i, err
}

const getNetworkByID = `-- name: GetNetworkByID :one
SELECT id, organization_id, name, description, type, subnet, gateway, dns_primary, dns_secondary, vlan_id, latitude, longitude, location_name, address, city, country_code, is_active, created_at FROM networks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNetworkByID(ctx context.Context, id uuid.UUID) (Network, error) {
	row := q.db.QueryRowContext(ctx, getNetworkByID, id)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Subnet,
		&i.Gateway,
		&i.DnsPrimary,
		&i.DnsSecondary,
		&i.VlanID,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.Address,
		&i.City,
		&i.CountryCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByAgentKey = `-- name: GetOrganizationByAgentKey :one
SELECT id, name, slug, email, password_hash, totp_secret, agent_registration_key, ip_allowlist, is_active, plan, created_at FROM organizations
WHERE agent_registration_key = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByAgentKey(ctx context.Context, agentRegistrationKey string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByAgentKey, agentRegistrationKey)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.AgentRegistrationKey,
		pq.Array(&i.IpAllowlist),
		&i.IsActive,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, email, password_hash, totp_secret, agent_registration_key, ip_allowlist, is_active, plan, created_at FROM organizations
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.AgentRegistrationKey,
		pq.Array(&i.IpAllowlist),
		&i.IsActive,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, totp_secret, is_active, last_login_at, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, totp_secret, is_active, last_login_at, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM user_organizations
WHERE user_id = $1 AND organization_id = $2 AND accepted_at IS NOT NULL
LIMIT 1
`

type GetUserRoleParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, arg.UserID, arg.OrganizationID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_logs (organization_id, user_id, action, target_type, target_id, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	OrganizationID uuid.NullUUID  `db:"organization_id" json:"organization_id"`
	UserID         uuid.NullUUID  `db:"user_id" json:"user_id"`
	Action         string         `db:"action" json:"action"`
	TargetType     string         `db:"target_type" json:"target_type"`
	TargetID       uuid.NullUUID  `db:"target_id" json:"target_id"`
	IpAddress      string         `db:"ip_address" json:"ip_address"`
	UserAgent      sql.NullString `db:"user_agent" json:"user_agent"`
}

// ============================================================
// AUDIT_LOGS
// ============================================================
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.OrganizationID,
		arg.UserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertCommandResult = `-- name: InsertCommandResult :one

INSERT INTO command_results (agent_id, command_id, command_str, output, exit_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, agent_id, command_id, command_str, output, exit_code, executed_at
`

type InsertCommandResultParams struct {
	AgentID    uuid.UUID      `db:"agent_id" json:"agent_id"`
	CommandID  string         `db:"command_id" json:"command_id"`
	CommandStr string         `db:"command_str" json:"command_str"`
	Output     sql.NullString `db:"output" json:"output"`
	ExitCode   int32          `db:"exit_code" json:"exit_code"`
}

// ============================================================
// COMMAND_RESULTS
// ============================================================
func (q *Queries) InsertCommandResult(ctx context.Context, arg InsertCommandResultParams) (CommandResult, error) {
	row := q.db.QueryRowContext(ctx, insertCommandResult,
		arg.AgentID,
		arg.CommandID,
		arg.CommandStr,
		arg.Output,
		arg.ExitCode,
	)
	var i CommandResult
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CommandID,
		&i.CommandStr,
		&i.Output,
		&i.ExitCode,
		&i.ExecutedAt,
	)
	return i, err
}

const insertMetric = `-- name: InsertMetric :one

INSERT INTO metrics (agent_id, cpu_percent, ram_percent, disk_percent, net_in_kbps, net_out_kbps)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, agent_id, cpu_percent, ram_percent, disk_percent, net_in_kbps, net_out_kbps, created_at
`

type InsertMetricParams struct {
	AgentID     uuid.UUID     `db:"agent_id" json:"agent_id"`
	CpuPercent  float32       `db:"cpu_percent" json:"cpu_percent"`
	RamPercent  float32       `db:"ram_percent" json:"ram_percent"`
	DiskPercent float32       `db:"disk_percent" json:"disk_percent"`
	NetInKbps   sql.NullInt32 `db:"net_in_kbps" json:"net_in_kbps"`
	NetOutKbps  sql.NullInt32 `db:"net_out_kbps" json:"net_out_kbps"`
}

// ============================================================
// METRICS
// ============================================================
func (q *Queries) InsertMetric(ctx context.Context, arg InsertMetricParams) (Metric, error) {
	row := q.db.QueryRowContext(ctx, insertMetric,
		arg.AgentID,
		arg.CpuPercent,
		arg.RamPercent,
		arg.DiskPercent,
		arg.NetInKbps,
		arg.NetOutKbps,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CpuPercent,
		&i.RamPercent,
		&i.DiskPercent,
		&i.NetInKbps,
		&i.NetOutKbps,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentsByNetwork = `-- name: ListAgentsByNetwork :many
SELECT id, network_id, token_hash, hostname, fqdn, os, distro, arch, kernel_version, ip_address, mac_address, agent_version, is_online, last_seen, latitude, longitude, location_name, city, country_code, created_at, user_organization_id, os_user, os_user_fullname, os_user_email FROM agents
WHERE network_id = $1
ORDER BY hostname
`

func (q *Queries) ListAgentsByNetwork(ctx context.Context, networkID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.TokenHash,
			&i.Hostname,
			&i.Fqdn,
			&i.Os,
			&i.Distro,
			&i.Arch,
			&i.KernelVersion,
			&i.IpAddress,
			&i.MacAddress,
			&i.AgentVersion,
			&i.IsOnline,
			&i.LastSeen,
			&i.Latitude,
			&i.Longitude,
			&i.LocationName,
			&i.City,
			&i.CountryCode,
			&i.CreatedAt,
			&i.UserOrganizationID,
			&i.OsUser,
			&i.OsUserFullname,
			&i.OsUserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByOrg = `-- name: ListAgentsByOrg :many
SELECT
    a.id, a.network_id, a.token_hash, a.hostname, a.fqdn, a.os, a.distro, a.arch, a.kernel_version, a.ip_address, a.mac_address, a.agent_version, a.is_online, a.last_seen, a.latitude, a.longitude, a.location_name, a.city, a.country_code, a.created_at, a.user_organization_id, a.os_user, a.os_user_fullname, a.os_user_email
    FROM agents a
    INNER JOIN networks n
    ON n.id = a.network_id
    WHERE n.organization_id = $1
    ORDER BY n.name, a.hostname
`

// TODO: escreva uma query que lista todos os agents de uma organização inteira
// (join agents → networks filtrando por networks.organization_id)
func (q *Queries) ListAgentsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.TokenHash,
			&i.Hostname,
			&i.Fqdn,
			&i.Os,
			&i.Distro,
			&i.Arch,
			&i.KernelVersion,
			&i.IpAddress,
			&i.MacAddress,
			&i.AgentVersion,
			&i.IsOnline,
			&i.LastSeen,
			&i.Latitude,
			&i.Longitude,
			&i.LocationName,
			&i.City,
			&i.CountryCode,
			&i.CreatedAt,
			&i.UserOrganizationID,
			&i.OsUser,
			&i.OsUserFullname,
			&i.OsUserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByUserOrg = `-- name: ListAgentsByUserOrg :many
SELECT id, network_id, token_hash, hostname, fqdn, os, distro, arch, kernel_version, ip_address, mac_address, agent_version, is_online, last_seen, latitude, longitude, location_name, city, country_code, created_at, user_organization_id, os_user, os_user_fullname, os_user_email FROM agents
WHERE user_organization_id = $1
ORDER BY hostname
`

func (q *Queries) ListAgentsByUserOrg(ctx context.Context, userOrganizationID uuid.NullUUID) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByUserOrg, userOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.TokenHash,
			&i.Hostname,
			&i.Fqdn,
			&i.Os,
			&i.Distro,
			&i.Arch,
			&i.KernelVersion,
			&i.IpAddress,
			&i.MacAddress,
			&i.AgentVersion,
			&i.IsOnline,
			&i.LastSeen,
			&i.Latitude,
			&i.Longitude,
			&i.LocationName,
			&i.City,
			&i.CountryCode,
			&i.CreatedAt,
			&i.UserOrganizationID,
			&i.OsUser,
			&i.OsUserFullname,
			&i.OsUserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT id, organization_id, user_id, action, target_type, target_id, ip_address, user_agent, created_at FROM audit_logs
WHERE organization_id = $1 AND created_at >= $2
ORDER BY created_at DESC
`

type ListAuditLogsByOrgParams struct {
	OrganizationID uuid.NullUUID `db:"organization_id" json:"organization_id"`
	CreatedAt      time.Time     `db:"created_at" json:"created_at"`
}

// TODO: escreva uma query que lista os últimos N audit logs de uma organização
func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByOrg, arg.OrganizationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommandResultsByAgent = `-- name: ListCommandResultsByAgent :many
SELECT id, agent_id, command_id, command_str, output, exit_code, executed_at FROM command_results
WHERE agent_id = $1
ORDER BY executed_at DESC
LIMIT $2
`

type ListCommandResultsByAgentParams struct {
	AgentID uuid.UUID `db:"agent_id" json:"agent_id"`
	Limit   int32     `db:"limit" json:"limit"`
}

// TODO: escreva uma query que lista os últimos N resultados de comandos de um agent
// dica: use LIMIT $2 e ORDER BY executed_at DESC
func (q *Queries) ListCommandResultsByAgent(ctx context.Context, arg ListCommandResultsByAgentParams) ([]CommandResult, error) {
	rows, err := q.db.QueryContext(ctx, listCommandResultsByAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommandResult{}
	for rows.Next() {
		var i CommandResult
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CommandID,
			&i.CommandStr,
			&i.Output,
			&i.ExitCode,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterfacesByAgent = `-- name: ListInterfacesByAgent :many
SELECT id, agent_id, interface_name, ip_address, mac_address, speed_mbps, is_up, updated_at FROM agent_network_interfaces
WHERE agent_id = $1
ORDER BY interface_name
`

func (q *Queries) ListInterfacesByAgent(ctx context.Context, agentID uuid.UUID) ([]AgentNetworkInterface, error) {
	rows, err := q.db.QueryContext(ctx, listInterfacesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentNetworkInterface{}
	for rows.Next() {
		var i AgentNetworkInterface
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.InterfaceName,
			&i.IpAddress,
			&i.MacAddress,
			&i.SpeedMbps,
			&i.IsUp,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricsSince = `-- name: ListMetricsSince :many
SELECT id, agent_id, cpu_percent, ram_percent, disk_percent, net_in_kbps, net_out_kbps, created_at FROM metrics
WHERE agent_id = $1 AND created_at >= $2
ORDER BY created_at ASC
`

type ListMetricsSinceParams struct {
	AgentID   uuid.UUID `db:"agent_id" json:"agent_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// TODO: escreva uma query que retorna as métricas de um agent a partir de uma data ($2)
// útil para montar gráficos no dashboard
func (q *Queries) ListMetricsSince(ctx context.Context, arg ListMetricsSinceParams) ([]Metric, error) {
	rows, err := q.db.QueryContext(ctx, listMetricsSince, arg.AgentID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Metric{}
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CpuPercent,
			&i.RamPercent,
			&i.DiskPercent,
			&i.NetInKbps,
			&i.NetOutKbps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworksByOrg = `-- name: ListNetworksByOrg :many
SELECT id, organization_id, name, description, type, subnet, gateway, dns_primary, dns_secondary, vlan_id, latitude, longitude, location_name, address, city, country_code, is_active, created_at FROM networks
WHERE organization_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListNetworksByOrg(ctx context.Context, organizationID uuid.UUID) ([]Network, error) {
	rows, err := q.db.QueryContext(ctx, listNetworksByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Network{}
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Subnet,
			&i.Gateway,
			&i.DnsPrimary,
			&i.DnsSecondary,
			&i.VlanID,
			&i.Latitude,
			&i.Longitude,
			&i.LocationName,
			&i.Address,
			&i.City,
			&i.CountryCode,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT u.id, u.email, u.password_hash, u.totp_secret, u.is_active, u.last_login_at, u.created_at, uo.accepted_at
    FROM
        users u
    INNER JOIN
        user_organizations uo
    ON
        u.id = uo.user_id
    WHERE
        uo.organization_id = $1
    AND
        uo.accepted_at IS NOT NULL
`

type ListOrganizationMembersRow struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	Email        string         `db:"email" json:"email"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	TotpSecret   sql.NullString `db:"totp_secret" json:"totp_secret"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	LastLoginAt  sql.NullTime   `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	AcceptedAt   sql.NullTime   `db:"accepted_at" json:"accepted_at"`
}

// TODO: escreva uma query que lista todos os membros de uma organização
// (join users + user_organizations filtrando por organization_id)
func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.TotpSecret,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByUser = `-- name: ListOrganizationsByUser :many
SELECT o.id, o.name, o.slug, o.email, o.password_hash, o.totp_secret, o.agent_registration_key, o.ip_allowlist, o.is_active, o.plan, o.created_at, uo.accepted_at
    FROM
        organizations o
    INNER JOIN
        user_organizations uo
    ON
        o.id = uo.organization_id
    WHERE
        uo.user_id = $1
    AND uo.accepted_at IS NOT NULL
`

type ListOrganizationsByUserRow struct {
	ID                   uuid.UUID      `db:"id" json:"id"`
	Name                 string         `db:"name" json:"name"`
	Slug                 string         `db:"slug" json:"slug"`
	Email                string         `db:"email" json:"email"`
	PasswordHash         string         `db:"password_hash" json:"password_hash"`
	TotpSecret           sql.NullString `db:"totp_secret" json:"totp_secret"`
	AgentRegistrationKey string         `db:"agent_registration_key" json:"agent_registration_key"`
	IpAllowlist          []string       `db:"ip_allowlist" json:"ip_allowlist"`
	IsActive             bool           `db:"is_active" json:"is_active"`
	Plan                 string         `db:"plan" json:"plan"`
	CreatedAt            time.Time      `db:"created_at" json:"created_at"`
	AcceptedAt           sql.NullTime   `db:"accepted_at" json:"accepted_at"`
}

// TODO: escreva uma query que retorna todas as organizations onde um user está inserido
// (join entre organizations e user_organizations filtrando por user_id e accepted_at IS NOT NULL)
func (q *Queries) ListOrganizationsByUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsByUserRow{}
	for rows.Next() {
		var i ListOrganizationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Email,
			&i.PasswordHash,
			&i.TotpSecret,
			&i.AgentRegistrationKey,
			pq.Array(&i.IpAllowlist),
			&i.IsActive,
			&i.Plan,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceDependencies = `-- name: ListServiceDependencies :many
SELECT s.id, s.agent_id, s.name, s.display_name, s.description, s.type, s.status, s.enabled, s.pid, s.run_as_user, s.port, s.protocol, s.restart_policy, s.health_check_cmd, s.health_check_url, s.last_health_check, s.health_status, s.uptime_seconds, s.updated_at FROM services s
JOIN service_dependencies sd ON sd.depends_on_id = s.id
WHERE sd.service_id = $1
`

func (q *Queries) ListServiceDependencies(ctx context.Context, serviceID uuid.UUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServiceDependencies, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.Enabled,
			&i.Pid,
			&i.RunAsUser,
			&i.Port,
			&i.Protocol,
			&i.RestartPolicy,
			&i.HealthCheckCmd,
			&i.HealthCheckUrl,
			&i.LastHealthCheck,
			&i.HealthStatus,
			&i.UptimeSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByAgent = `-- name: ListServicesByAgent :many
SELECT id, agent_id, name, display_name, description, type, status, enabled, pid, run_as_user, port, protocol, restart_policy, health_check_cmd, health_check_url, last_health_check, health_status, uptime_seconds, updated_at FROM services
WHERE agent_id = $1
ORDER BY name
`

func (q *Queries) ListServicesByAgent(ctx context.Context, agentID uuid.UUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.Enabled,
			&i.Pid,
			&i.RunAsUser,
			&i.Port,
			&i.Protocol,
			&i.RestartPolicy,
			&i.HealthCheckCmd,
			&i.HealthCheckUrl,
			&i.LastHealthCheck,
			&i.HealthStatus,
			&i.UptimeSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyByNetwork = `-- name: ListTopologyByNetwork :many
SELECT id, network_a_id, network_b_id, link_type, description, created_at FROM network_topology
WHERE network_a_id = $1 OR network_b_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTopologyByNetwork(ctx context.Context, networkAID uuid.UUID) ([]NetworkTopology, error) {
	rows, err := q.db.QueryContext(ctx, listTopologyByNetwork, networkAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkTopology{}
	for rows.Next() {
		var i NetworkTopology
		if err := rows.Scan(
			&i.ID,
			&i.NetworkAID,
			&i.NetworkBID,
			&i.LinkType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerAgent = `-- name: RegisterAgent :one

INSERT INTO agents (network_id, token_hash, hostname, fqdn, os, distro, arch, kernel_version, ip_address, mac_address, agent_version, latitude, longitude, location_name, city, country_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, network_id, token_hash, hostname, fqdn, os, distro, arch, kernel_version, ip_address, mac_address, agent_version, is_online, last_seen, latitude, longitude, location_name, city, country_code, created_at, user_organization_id, os_user, os_user_fullname, os_user_email
`

type RegisterAgentParams struct {
	NetworkID     uuid.UUID      `db:"network_id" json:"network_id"`
	TokenHash     string         `db:"token_hash" json:"token_hash"`
	Hostname      string         `db:"hostname" json:"hostname"`
	Fqdn          sql.NullString `db:"fqdn" json:"fqdn"`
	Os            string         `db:"os" json:"os"`
	Distro        sql.NullString `db:"distro" json:"distro"`
	Arch          string         `db:"arch" json:"arch"`
	KernelVersion sql.NullString `db:"kernel_version" json:"kernel_version"`
	IpAddress     string         `db:"ip_address" json:"ip_address"`
	MacAddress    sql.NullString `db:"mac_address" json:"mac_address"`
	AgentVersion  string         `db:"agent_version" json:"agent_version"`
	Latitude      sql.NullString `db:"latitude" json:"latitude"`
	Longitude     sql.NullString `db:"longitude" json:"longitude"`
	LocationName  sql.NullString `db:"location_name" json:"location_name"`
	City          sql.NullString `db:"city" json:"city"`
	CountryCode   sql.NullString `db:"country_code" json:"country_code"`
}

// ============================================================
// AGENTS
// ============================================================
func (q *Queries) RegisterAgent(ctx context.Context, arg RegisterAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, registerAgent,
		arg.NetworkID,
		arg.TokenHash,
		arg.Hostname,
		arg.Fqdn,
		arg.Os,
		arg.Distro,
		arg.Arch,
		arg.KernelVersion,
		arg.IpAddress,
		arg.MacAddress,
		arg.AgentVersion,
		arg.Latitude,
		arg.Longitude,
		arg.LocationName,
		arg.City,
		arg.CountryCode,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.TokenHash,
		&i.Hostname,
		&i.Fqdn,
		&i.Os,
		&i.Distro,
		&i.Arch,
		&i.KernelVersion,
		&i.IpAddress,
		&i.MacAddress,
		&i.AgentVersion,
		&i.IsOnline,
		&i.LastSeen,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.City,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UserOrganizationID,
		&i.OsUser,
		&i.OsUserFullname,
		&i.OsUserEmail,
	)
	return i, err
}

const setAgentOffline = `-- name: SetAgentOffline :exec
UPDATE agents SET is_online = false
WHERE id = $1
`

func (q *Queries) SetAgentOffline(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setAgentOffline, id)
	return err
}

const setOfflineAgentsSince = `-- name: SetOfflineAgentsSince :exec
UPDATE agents SET is_online = false
WHERE last_seen < NOW() - ($1::interval) AND is_online = true
`

// marca offline todos os agents que não mandam heartbeat há X tempo
// $1 é um intervalo: ex '2 minutes'
func (q *Queries) SetOfflineAgentsSince(ctx context.Context, dollar_1 string) error {
	_, err := q.db.ExecContext(ctx, setOfflineAgentsSince, dollar_1)
	return err
}

const updateAgentLastSeen = `-- name: UpdateAgentLastSeen :exec
UPDATE agents SET last_seen = NOW(), is_online = true
WHERE id = $1
`

func (q *Queries) UpdateAgentLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAgentLastSeen, id)
	return err
}

const updateServiceHealth = `-- name: UpdateServiceHealth :exec
UPDATE services SET health_status = $1, last_health_check = NOW()
WHERE id = $2
`

type UpdateServiceHealthParams struct {
	HealthStatus sql.NullString `db:"health_status" json:"health_status"`
	ID           uuid.UUID      `db:"id" json:"id"`
}

// TODO: escreva uma query para atualizar o health_status e last_health_check de um serviço pelo id
func (q *Queries) UpdateServiceHealth(ctx context.Context, arg UpdateServiceHealthParams) error {
	_, err := q.db.ExecContext(ctx, updateServiceHealth, arg.HealthStatus, arg.ID)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const upsertAgentHardware = `-- name: UpsertAgentHardware :one

INSERT INTO agent_hardware (agent_id, cpu_model, cpu_cores, cpu_threads, ram_total_bytes, disk_total_bytes, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (agent_id) DO UPDATE SET
  cpu_model        = EXCLUDED.cpu_model,
  cpu_cores        = EXCLUDED.cpu_cores,
  cpu_threads      = EXCLUDED.cpu_threads,
  ram_total_bytes  = EXCLUDED.ram_total_bytes,
  disk_total_bytes = EXCLUDED.disk_total_bytes,
  updated_at       = NOW()
RETURNING agent_id, cpu_model, cpu_cores, cpu_threads, ram_total_bytes, disk_total_bytes, updated_at
`

type UpsertAgentHardwareParams struct {
	AgentID        uuid.UUID `db:"agent_id" json:"agent_id"`
	CpuModel       string    `db:"cpu_model" json:"cpu_model"`
	CpuCores       int32     `db:"cpu_cores" json:"cpu_cores"`
	CpuThreads     int32     `db:"cpu_threads" json:"cpu_threads"`
	RamTotalBytes  int64     `db:"ram_total_bytes" json:"ram_total_bytes"`
	DiskTotalBytes int64     `db:"disk_total_bytes" json:"disk_total_bytes"`
}

// ============================================================
// AGENT_HARDWARE
// ============================================================
func (q *Queries) UpsertAgentHardware(ctx context.Context, arg UpsertAgentHardwareParams) (AgentHardware, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentHardware,
		arg.AgentID,
		arg.CpuModel,
		arg.CpuCores,
		arg.CpuThreads,
		arg.RamTotalBytes,
		arg.DiskTotalBytes,
	)
	var i AgentHardware
	err := row.Scan(
		&i.AgentID,
		&i.CpuModel,
		&i.CpuCores,
		&i.CpuThreads,
		&i.RamTotalBytes,
		&i.DiskTotalBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentNetworkInterface = `-- name: UpsertAgentNetworkInterface :one

INSERT INTO agent_network_interfaces (agent_id, interface_name, ip_address, mac_address, speed_mbps, is_up)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (agent_id, interface_name) DO UPDATE SET
    ip_address = EXCLUDED.ip_address,
    mac_address = EXCLUDED.mac_address,
    speed_mbps = EXCLUDED.speed_mbps,
    is_up = EXCLUDED.is_up,
    updated_at = NOW()
RETURNING id, agent_id, interface_name, ip_address, mac_address, speed_mbps, is_up, updated_at
`

type UpsertAgentNetworkInterfaceParams struct {
	AgentID       uuid.UUID      `db:"agent_id" json:"agent_id"`
	InterfaceName string         `db:"interface_name" json:"interface_name"`
	IpAddress     string         `db:"ip_address" json:"ip_address"`
	MacAddress    sql.NullString `db:"mac_address" json:"mac_address"`
	SpeedMbps     sql.NullInt32  `db:"speed_mbps" json:"speed_mbps"`
	IsUp          bool           `db:"is_up" json:"is_up"`
}

// ============================================================
// AGENT_NETWORK_INTERFACES
// ============================================================
func (q *Queries) UpsertAgentNetworkInterface(ctx context.Context, arg UpsertAgentNetworkInterfaceParams) (AgentNetworkInterface, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentNetworkInterface,
		arg.AgentID,
		arg.InterfaceName,
		arg.IpAddress,
		arg.MacAddress,
		arg.SpeedMbps,
		arg.IsUp,
	)
	var i AgentNetworkInterface
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.InterfaceName,
		&i.IpAddress,
		&i.MacAddress,
		&i.SpeedMbps,
		&i.IsUp,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertService = `-- name: UpsertService :one

INSERT INTO services (agent_id, name, display_name, type, status, enabled, pid, uptime_seconds, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (agent_id, name) DO UPDATE SET
  status         = EXCLUDED.status,
  enabled        = EXCLUDED.enabled,
  pid            = EXCLUDED.pid,
  uptime_seconds = EXCLUDED.uptime_seconds,
  updated_at     = NOW()
RETURNING id, agent_id, name, display_name, description, type, status, enabled, pid, run_as_user, port, protocol, restart_policy, health_check_cmd, health_check_url, last_health_check, health_status, uptime_seconds, updated_at
`

type UpsertServiceParams struct {
	AgentID       uuid.UUID     `db:"agent_id" json:"agent_id"`
	Name          string        `db:"name" json:"name"`
	DisplayName   string        `db:"display_name" json:"display_name"`
	Type          string        `db:"type" json:"type"`
	Status        string        `db:"status" json:"status"`
	Enabled       bool          `db:"enabled" json:"enabled"`
	Pid           sql.NullInt32 `db:"pid" json:"pid"`
	UptimeSeconds int64         `db:"uptime_seconds" json:"uptime_seconds"`
}

// ============================================================
// SERVICES
// ============================================================
func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, upsertService,
		arg.AgentID,
		arg.Name,
		arg.DisplayName,
		arg.Type,
		arg.Status,
		arg.Enabled,
		arg.Pid,
		arg.UptimeSeconds,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Enabled,
		&i.Pid,
		&i.RunAsUser,
		&i.Port,
		&i.Protocol,
		&i.RestartPolicy,
		&i.HealthCheckCmd,
		&i.HealthCheckUrl,
		&i.LastHealthCheck,
		&i.HealthStatus,
		&i.UptimeSeconds,
		&i.UpdatedAt,
	)
	return i, err
}

const useInvite = `-- name: UseInvite :exec
UPDATE organization_invites SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) UseInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, useInvite, id)
	return err
}
